home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.landingPage, name='landingPage'),
    path('home/', views.home, name='home')
]

playlist/urls.py
from django.urls import path
from . import views

app_name = 'playlist'

urlpatterns = [
    path('', views.playlist, name='playlist'),
]

productivity/urls.py
from django.urls import path
from .views import activity

app_name = 'productivity'

urlpatterns = [
    path('productivity-tracker/', activity, name='activity'),
]

quotesgen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.quotesgen, name = 'quotesgen')
]

tk1proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('productivity.urls')),
    path('quotes/', include('quotesgen.urls')),
    path('playlist/', include('playlist.urls')),
]

home/models.py
from django.db import models

# Create your models here.


class Name(models.Model):
    name = models.CharField(max_length=100, blank=False, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'name'

playlist/models.py
from django.db import models

# Create your models here.


class Comment(models.Model):
    name = models.CharField(max_length=100, blank=False, null=True)
    comment = models.CharField(max_length=150, blank=False, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'comment'

productivity/models.py
from django.db import models

class Activity(models.Model):
    activity = models.CharField(max_length=100)

quotesgen/models.py
from django.db import models

# Create your models here.
class Quote(models.Model):
    quote = models.TextField('Quote', max_length=200, null=True, blank=False)

    def __str__(self):
        return f'{self.quote}'

    class Meta:
        db_table = 'quote'

home/forms.py
from django.forms import ModelForm
from .models import Name
from django import forms


class NameForm(forms.ModelForm):
    #    name = forms.CharField(label='name', max_length=30, required=True)
    name = forms.CharField(widget=forms.Textarea, label='', required=True)

    class Meta:
        model = Name
        fields = ['name']

playlist/forms.py
from django.forms import ModelForm
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','comment']

        widgets = {
            'name': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Your name here.',
                'required':True,}),
            'comment': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'Your comment here.',
                'required':True}),
        }

productivity/forms.py
from django import forms
from .models import Activity

class ActivityForm(forms.Form):
    activity = forms.CharField(max_length=100)

home/views.py
from django.shortcuts import render, redirect
from .models import Name
from .forms import NameForm
from django.http import HttpResponse
# Create your views here.


def home(request):
    save = "Someone"
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            save = form.save()
    context = {
        'name': save
    }
    return render(request, 'home.html', context)


def landingPage(request):
    form = NameForm()
    context = {
        'form': form,
    }
    return render(request, 'landingPage.html', context)

playlist/views.py
from django.shortcuts import render, redirect
from .models import Comment
from .forms import CommentForm
from django.http import HttpResponseRedirect
# Create your views here.


def playlist(request):
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid:
            form.save()
            form = CommentForm()
            return HttpResponseRedirect('/playlist/')
    else:
        form = CommentForm()
        comments = Comment.objects.all()
        context = {
            'comments':comments,
            'form':form
        }
        return render(request, 'playlist.html', context)

productivity/views.py
from django.shortcuts import render, redirect
from .models import Activity
from .forms import ActivityForm
from django.contrib import messages

def activity(request):
    form = ActivityForm()
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            Activity.objects.create(**form.cleaned_data)
            messages.success(request, (f"Activity '{request.POST['activity']}' was successfully added !"))
            return redirect('productivity:activity')
        else:
            messages.warning(request, (f"Wrong input!"))
            return redirect('productivity:activity')
    context = {
        'form' : form,
        'activities' : Activity.objects.all()
    }
    return render(request, "tracker.html", context)

quotesgen/views.py
from django.shortcuts import render
from .models import Quote
from django.db.models import Max
import random


# Create your views here.
def quotesgen(request):
    if request.method == 'POST':
        max_id = Quote.objects.all().aggregate(max_id=Max("id"))['max_id']
        pk = random.randint(29, max_id)
        return render(request, 'quotes_gen.html', {'quotefinal': Quote.objects.get(pk=pk)})
    else:
        return render(request, 'quotes_gen.html')

home/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ section.title }}{% endblock %}

{% block link %}
<link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'home.css' %}" />
{% endblock %}

{% block content %}
<div class="top">
  <div class="divIcon">
    <img id="icon" src="{% static 'icon1.png' %}">
  </div>
  <div class="home-top">
    <h1 id="hello"> Hello, <span id="someone">{{ name }}</span>!</h1>
    <p id="slogan">Take a deep breath and rest your soul :)</p>
  </div>
  <div class="divIcon">
    <img id="icon1" src="{% static 'icon1.png' %}">
    <img id="icon2" src="{% static 'icon2.png' %}">
  </div>
</div>

<h4 id="reach">reach out!</h4>
<div class="contact">
  <p id="contact" style="text-align: center">contact a professional</p>
</div>


<div class="container-slider">
  <div class="box">
    <a href="https://www.instagram.com/inezkristanti/">
      <img class="imgDesign" src="{% static 'inez2.png' %}">
    </a>
    <h4 class="psyName">Inez Kristanti</h4>
    <p class="psyTitle">Clinical Psychologist</p>
  </div>
  <div class="box">
    <a href="https://www.instagram.com/babyjimaditya/?hl=id">
      <img class="imgDesign" src="{% static 'baby2.jpg' %}">
    </a>
    <h4 class="psyName">Baby Jim Aditya</h4>
    <p class="psyTitle">Sexual Psychologist</p>
  </div>
  <div class="box">
    <a href="https://www.instagram.com/nadyapramesrani/?hl=id">
      <img class="imgDesign" src="{% static 'nadya2.jpg' %}">
    </a>
    <h4 class="psyName">Nadya Pramesrani</h4>
    <p class="psyTitle">Clinical Psychologist</p>
  </div>
  <div class="box">
    <a href="https://www.instagram.com/andiniskayanti/">
      <img class="imgDesign" src="{% static 'andini2.png' %}">
    </a>
    <h4 class="psyName">Andini Iskayanti</h4>
    <p class="psyTitle">Clinical Psychologist</p>
  </div>
  <div class="box">
    <a href="https://www.instagram.com/verauli.id/?hl=id">
      <img class="imgDesign" src="{% static 'roslina2.png' %}">
    </a>
    <h4 class="psyName">Roslina Verauli</h4>
    <p class="psyTitle">Family Psychologist</p>
  </div>
  <div class="box">
    <a href="https://www.instagram.com/nidyadwikaputeri/">
      <img class="imgDesign" src="{% static 'nidya2.png' %}">
    </a>
    <h4 class="psyName">Nidya Dwika Puteri</h4>
    <p class="psyTitle">Child Psychologist</p>
  </div>
</div>


{% endblock %}

home/templates/landingPage.html
{% load static %}
{% block title %}{{ section.title }}{% endblock %}

{% block link %}
<link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'landingPage.css' %}">
{% endblock %}
{% block content %}
<div class="col-lg-12; containerLandingPage ">
    <div class="col-lg-6; sisiKiri">
        <div class="name">
            <p class="words">
                Do you mind telling us
                <span id="yourName">your name</span>?
            </p>
        </div>
        <div class="addName">
            <form action="home/" method="POST" novalidate>
                {% csrf_token %}
                {{ form }}
                <div class="correct">
                    <input id="correct" type="submit" value="THAT'S CORRECT!">
                </div>
            </form>
        </div>
    </div>
    <div class="sisiKanan;col-lg-6">
        <div class="icon">
            <img id="icon" src="{% static 'icon3.png' %}">
        </div>
    </div>
</div>

{% endblock %}

playlist/templates/playlist.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ section.title }}{% endblock %}

{% block link %}
<link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'playlist.css' %}" />
{% endblock %}

{% block content %}
<body>

<h1 class="judul1">Play<span class="judul2">list</span> </h1>

<div class="d-flex flex-row bd-highlight mb-3">
    <a href="https://open.spotify.com/track/2IAR0DziHCjSu16gR4ihvy?si=qSEGNx2IQ8CWrgmR1XpY0A"><img src="/static/cover1.png"></a>
    <a href="https://open.spotify.com/track/630DpnzdfjdVqv2yLfPbAX?si=cpGIf49tTBKwggHEXd0nmg"><img src="/static/cover2.png"></a>
    <a href="https://open.spotify.com/track/45PxuJqJBnPXZKLxoo9Apj?si=yG6D5RFWSXeMQePyIQQrew"><img src="/static/cover3.png"></a>
</div>

<div class="d-flex flex-row bd-highlight mb-3" id="titles">
    <div> &nbsp;  &nbsp; Nothing &nbsp;  &nbsp;  &nbsp; &nbsp; </div>
    <div> &nbsp;  &nbsp; &nbsp; &nbsp; Bertaut &nbsp;  &nbsp;  &nbsp; </div>
    <div> &nbsp;  &nbsp; Superposition</div>
</div>

<div class="d-flex flex-row bd-highlight mb-3" id="artists">
    <div> &nbsp;  &nbsp; &nbsp; Bruno Major &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; </div>
    <div> &nbsp;  &nbsp; &nbsp; &nbsp; Nadin Amizah &nbsp;  &nbsp;  &nbsp; &nbsp;</div>
    <div> &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Daniel Caesar </div>
</div>

<div class="d-flex flex-row bd-highlight mb-3" id="secondrow">
    <a href="https://open.spotify.com/track/4EWBhKf1fOFnyMtUzACXEc?si=mS_Faf80RmO0uc3Vw2zIsg"><img src="/static/cover4.png"></a>
    <a href="https://open.spotify.com/track/6aDyiU2cVrqh33UEnEo3WA?si=cbf64bvCSLCtjn14BiS0EA"><img src="/static/cover5.png"></a>
    <a href="https://open.spotify.com/track/4ZG4aqyBvKk3V3yZBoLToK?si=wqsy4nUsQVio9rZfWOwnmg"><img src="/static/cover6.png"></a>
</div>

<div class="d-flex flex-row bd-highlight mb-3" id="titles2">
    <div>  Pluto Projector  &nbsp; </div>
    <div> &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; 6/10 &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp; </div>
    <div> &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp; Sulung </div>
</div>

<div class="d-flex flex-row bd-highlight mb-3" id="artists2">
    <div> &nbsp;  Rex Orange County &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp;  </div>
    <div> &nbsp;  &nbsp; &nbsp; &nbsp; Dodie &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; </div>
    <div> &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kunto Aji </div>
</div>

<h3 id="judulTambahKomen">What do you think of the playlist?</h3>


<div class="flex-container" id="formrow2">
    <div class="addName">
        <form action="/playlist/" method="POST">
            {% csrf_token %}
            <h3 class="tambahKomen">Name:</h3>
            {{ form.name }}
            <h3 class="tambahKomen">Comment:</h3>
            {{ form.comment }}
            <button class="btn rounded-pill">Submit</button>
        </form>
    </div>
</div>

<h3 class="judulKomen">Comments</h3>

<div class="row">
        {% for comment in comments %}
            <div class="card quotes">
                    <div class="card-body">
                        <h5 class="card-title"><i>{{ comment.comment }}</h5>
                        <p class="card-text"><hr>{{ comment.name }}</p>
                    </div>
                {% endfor %}
                </div>
            </div>
</div>

</body>
{% endblock content %}

quotesgen/templates/quotes_gen.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ section.title }}{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/quotesgen.css' %}" />
<div class=default >
    <h1 class="title2" style="text-align: center;"> <span>Quotes</span></h1>
    <h1 class="title3 "style="text-align: center; line-height: 1vw;"> for you today.</h1>
</div>

<div class="container">
    <div class="center">
        <form method="POST" action="">
            <button type="submit" value="Submit" class="button3">GENERATE</button>
            {% csrf_token %}
        </form>
    </div>
</div>
<div id="quotes" style="margin-top: 1vw;">
    <div class="center2">
        <p style="text-align: center;" >{{ quotefinal }}</p>
    </div>
</div>

<div class=show-on-mobile>
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player class="lottie" src="https://assets1.lottiefiles.com/private_files/lf30_emydabyz.json" mode="bounce" background="transparent"  speed="0.5"  style="width:100%"  loop  autoplay></lottie-player>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Bootstrap CSS -->
  <link rel="icon" href="{% static 'img/favicon.ico' %}" />
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block link %}
  {% endblock %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tracker.css' %}" />

  <title> Rest your soul. </title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#">
      <div class="title" style="font-family: 'Abril Fatface', cursive;"> rest your <span> soul. </span> </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'quotesgen' %}"> QUOTES </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'playlist:playlist' %}"> PLAYLIST </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'productivity:activity' %}"> PRODUCTIVITY</a>
        </li>
      </ul>
    </div>
  </nav>


  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
  {% block content %}
  {% endblock %}

  <div class="footer">
    <p id="footer"> &copy; Copyright 2020 Group G-1 <span>Rest Your Soul</span>. All Rights Deserved.
    </p>
  </div>

</body>
</html>

templates/tracker.html
{% extends 'base.html' %}
{% block content %}

<div class="container py-4">
    <h1 class="toDo_title">Things <span>to-do</span></h1>
    <p id="better"><i>that make you <strong>feel better</strong></i></p>
    
    <Form method="POST" class="row my-5" id="form">
        {% csrf_token %}
        <div class="toDo_insert">
            {{ form.activity }}
        </div>
        <button type="submit" class="btn toDo_add">Add</button>
    </Form>

    <hr>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}

    <div class="toDo_list">
        <div class="flex-container">
            <div class="btn-group-toggle " data-toggle="buttons">
                <label class="btn checkmark active">
                    <input type="checkbox" checked><span class = "checkmark"></span>
                </label>
            </div>   
            <div class="card list">
                <h5 class="activity col-10">tidur</h5>   
            </div>
        </div>
        {% for activity in activities %}
        <div class="flex-container">
            <div class="btn-group-toggle " data-toggle="buttons">
                <label class="btn checkmark active">
                    <input type="checkbox"><span class = "checkmark"></span>
                </label>
            </div>   
            <div class="card list">
                <h5 class="activity col-10">{{ activity.activity }}</h5>   
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="card quotes">
        <div class="card-body">
          <h5 class="card-title"><i>"Part of the <strong>healing</strong> process is 
                <strong>sharing</strong> with other people who care"</i></h5>
          <p class="card-text"><hr>- Jerry Cantrell -</p>
        </div>
    </div>

    <div class ="row">
        <div class="col-lg-6">
            <div class="foto-pusing"></div>
        </div>
        <div class="col-lg-6">                    
            <div class="semangat">
                <p>Have a wonderful day !
                    <!-- <br><b> {{name}} </b>! -->
                </p>
            </div>
        </div>
    </div>
    
</div>

{% endblock content %}